name: "Perk.Exchange Payment"
description: "Accept payments from users"
author: "Geoff Whittington"
inputs:
  apiToken:
    description: "API Token"
    default: ""
  amount:
    description: "Reward amount"
    default: "1"
  currency:
    description: "Reward currency"
    default: "USD"
  orderId:
    description: "Unique payment identifier"
    default: "{owner}/{repo}/{branch}"
  server:
    description: "Perk.Exchange server"
    default: "https://perk.exchange"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'dollar-sign'  
  color: 'purple'
